### ISSUE TITLE
Release into melodic

### ISSUE THREAD

**Issue by sloretz** [ros/urdf_parser_py#27]
Looks like no other repos are blocking this one from being released into melodic.

http://repositories.ros.org/status_page/blocked_releases_melodic.html?q=id%3D%22urdfdom_py%22&s=6&r=1

- [x] Merge pull request #26
- [x] Merge pull request #14
- [x] Add in backwards compatibility hooks for changes in #26 (#28)
- [x] Release (https://github.com/ros/rosdistro/pull/17025)

**Comment by clalancette** [comment]
Done, closing.
